const sqlite3 = require('sqlite3').verbose();
const path = require('path');
const dbPath = path.resolve(__dirname, 'database.sqlite');
const db = new sqlite3.Database(dbPath);

const cities = [
    { city: "Mumbai", country: "India", basePrice: 4000, category: "luxury" },
    { city: "Delhi", country: "India", basePrice: 3500, category: "business" },
    { city: "Bangalore", country: "India", basePrice: 3000, category: "business" },
    { city: "Goa", country: "India", basePrice: 5000, category: "resort" },
    { city: "Jaipur", country: "India", basePrice: 3200, category: "boutique" },
    { city: "Udaipur", country: "India", basePrice: 4500, category: "luxury" },
    { city: "Kerala", country: "India", basePrice: 3800, category: "resort" },
    { city: "Chennai", country: "India", basePrice: 2800, category: "business" },
];

const types = ["Hotel", "Apartment", "Resort", "Villa", "Loft"];
const amenitiesList = ["WiFi", "Pool", "Gym", "Spa", "Restaurant", "Parking", "Bar"];
const propertyImages = [
    "https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&q=80&w=1000",
    "https://images.unsplash.com/photo-1582719508461-905c673771fd?auto=format&fit=crop&q=80&w=1000",
    "https://images.unsplash.com/photo-1596394516093-501ba68a0ba6?auto=format&fit=crop&q=80&w=1000",
    "https://images.unsplash.com/photo-1590490360182-c33d57733427?auto=format&fit=crop&q=80&w=1000",
    "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?auto=format&fit=crop&q=80&w=1000"
];

function getRandomSubarray(arr, size) {
    var shuffled = arr.slice(0), i = arr.length, min = i - size, temp, index;
    while (i-- > min) {
        index = Math.floor((i + 1) * Math.random());
        temp = shuffled[index];
        shuffled[index] = shuffled[i];
        shuffled[i] = temp;
    }
    return shuffled.slice(min);
}

db.serialize(() => {
    const stmt = db.prepare(`INSERT INTO properties (user_id, name, slug, description, price, location, city, country, type, amenities, images, currency, category) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`);

    cities.forEach(dest => {
        console.log(`Seeding properties for ${dest.city}...`);
        for (let i = 1; i <= 10; i++) {
            const type = types[Math.floor(Math.random() * types.length)];
            const name = `${dest.city} ${type} ${i}`;
            const slug = name.toLowerCase().replace(/[^a-z0-9]+/g, '-') + '-' + Date.now() + i;
            const price = dest.basePrice + Math.floor(Math.random() * 2000) - 500;
            const description = `Experience the best of ${dest.city} in this beautiful ${type.toLowerCase()}. Located near top attractions with premium amenities.`;
            const amenities = JSON.stringify(getRandomSubarray(amenitiesList, 4));
            // Use random images
            const images = JSON.stringify(getRandomSubarray(propertyImages, 3));

            // Assume user_id 1 exists (autogenerated usually) or use arbitrary ID
            stmt.run(1, name, slug, description, price, "City Center", dest.city, dest.country, type, amenities, images, "INR", dest.category);
        }
    });

    stmt.finalize((err) => {
        if (err) {
            console.error("Error seeding:", err);
        } else {
            console.log("Seeding complete. 60 properties added.");
        }
    });
});

db.close();
